sudo: false

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  # use specific versions in case something breaks
  - pip install tox-travis==0.11 tox==3.7.0

script:
  # run tox
  - tox

  # use this version of py-commit-checker to check itself, in emoji mode!
  - pip install -e . &&
    PY_COMMIT_CHECKER_ARGS='--emojis' py-commit-checker-branch origin/master
